---
- hosts: all
  become: yes
  become_method: sudo
  gather_facts: False
  vars:
    oracle_java_version: "11" # change this to the version you want to check
  tasks:
    - name: Find all Java binaries excluding different filesystems
      shell: find / -type f -name java 2>/dev/null -not -fstype nfs -and -not -fstype proc -and -not -fstype sysfs -and -not -fstype devpts
      timeout: "{{ timeout | default(600) }}"
      register: 'java_files'

    - name: Get the version of each Java binary
      shell: "{{ item }} -version 2>&1 | grep version | awk '{print $3}' | sed 's/\"//g'"
      with_items: "{{ java_files.stdout_lines }}"
      register: 'java_version'

    - name: Print all stdout values from java_version
      ansible.builtin.debug:
        msg: "{{ java_version | json_query('results[*].stdout') }}"
      when: java_version is defined

    - name: Check if any Java version is equal or higher than Oracle Java version
      set_fact:
        java_check: true
      loop: "{{ java_version.results }}"
      when:
        - item.stdout is defined
        - item.stdout is version(oracle_java_version, '>=')

    - name: Display a message if Java check is true
      debug:
        msg: "You have Oracle Java {{ oracle_java_version }} or higher installed"
      when: java_check is defined and java_check
